# Linear network: Alice - Bob - Charlie - David
# Goal 5: Hardware Realistic Parameters

# Standardized Device Config
noisy_qdevice_cfg: &noisy_qdevice_cfg
  num_qubits: 2
  T1: 500000000
  T2: 500000000
  init_time: 10000
  single_qubit_gate_time: 10000
  two_qubit_gate_time: 10000
  measure_time: 10000
  single_qubit_gate_depolar_prob: 0.005
  two_qubit_gate_depolar_prob: 0.005

stacks:
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      <<: *noisy_qdevice_cfg
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      <<: *noisy_qdevice_cfg
  - name: Charlie
    qdevice_typ: generic
    qdevice_cfg:
      <<: *noisy_qdevice_cfg
  - name: David
    qdevice_typ: generic
    qdevice_cfg:
      <<: *noisy_qdevice_cfg

links:
  - stack1: Alice
    stack2: Bob
    typ: depolarise
    cfg:
      fidelity: 0.97
      prob_success: 0.2
      length: 10
  - stack1: Bob
    stack2: Charlie
    typ: depolarise
    cfg:
      fidelity: 0.97
      prob_success: 0.2
      length: 10
  - stack1: Charlie
    stack2: David
    typ: depolarise
    cfg:
      fidelity: 0.97
      prob_success: 0.2
      length: 10

clinks:
  - stack1: Alice
    stack2: Bob
    typ: default
    length: 10
  - stack1: Bob
    stack2: Charlie
    typ: default
    length: 10
  - stack1: Charlie
    stack2: David
    typ: default
    length: 10